---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: columns
    vertical_layout: fill
    source_code: "https://github.com/E-Fernandez-Albuquerque/app-R-acoes"
runtime: shiny #Interação
---

```{r setup, include=FALSE}
#Dashboard
library(flexdashboard)

#Gráficos
library(ggplot2)
library(plotly)

#Tabelas
library(dplyr)

#Dados financeiros
library(tidyquant)
```

Column {.sidebar data-width=150}
-----------------------------------------------------------------------
```{r}
selectInput(
  "ticker", 
  "Escolha o ticker:", 
  choices = c("OIBR3.SA", "MGLU3.SA", "AMER3.SA", "CVCB3.SA", "PETZ3.SA")
)
```



```{r download}
dados_tbl <- reactive({
  tq_get(input$ticker)
})
```


Column {data-width=450}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  dados_tbl() %>% 
    select(date, adjusted) %>% 
    arrange(desc(date))
}, options = list (iDisplayLength = 10))

```

Column {data-width=550}
-----------------------------------------------------------------------

### Gráfico da ação

```{r}
renderPlotly({
  dados_tbl() %>%
    ggplot(aes(x = date, y = adjusted)) +
    geom_line(colour='#6121dc') +
    theme_minimal()
})
```

### Gráfico comparativo

```{r}
renderPlotly({
  tq_get(c("OIBR3.SA", "MGLU3.SA", "AMER3.SA", "CVCB3.SA", "PETZ3.SA")) %>%
    group_by(symbol) %>% 
    mutate(cotacao = (adjusted - mean(adjusted)) / sd(adjusted)) %>% 
    ungroup() %>% 
    ggplot(aes(x = date, y = cotacao, color = symbol)) +
    geom_line() + 
    theme_minimal()
})
```